'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let csrf='',state,tab='overview',dirty=false,editing,media=[],pickCallback,toastTimer,uploading=0;
async function api(url,method='GET',data){const r=await fetch('/api/admin/'+url,{method,headers:{...(method!=='GET'?{'X-CSRF-Token':csrf}:{}),...(data!==undefined?{'Content-Type':'application/json'}:{})},body:data===undefined?undefined:JSON.stringify(data)});const value=await r.json();if(!r.ok)throw Error(value.error||'Request failed');return value;}
function toast(message){if($('#project-dialog').open)$('#project-error').textContent=message;$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,6000);}
function changed(){dirty=true;$('#save-status').textContent='Unsaved changes';}
function accept(next){state=next;dirty=false;$('#save-status').textContent='Draft saved · Not published';}
async function publishChanges(){if(uploading)throw Error('Wait for uploads to finish before publishing.');if(dirty)await save();const workspace=$('#workspace');workspace.inert=true;try{accept(await api('publish','POST',{version:state.version}));$('#save-status').textContent='Published - Website updated';toast('Published successfully. Your website is updated.');}finally{workspace.inert=false;}}
async function save(){const workspace=$('#workspace');workspace.inert=true;try{accept(await api('draft','PUT',{version:state.version,content:state.draft}));toast('Draft saved. Preview it before publishing.');}finally{workspace.inert=false;}}
function confirmAction(title,message){return new Promise(resolve=>{const d=$('#confirm-dialog');$('#confirm-title').textContent=title;$('#confirm-message').textContent=message;d.showModal();let result=false;$('#confirm-ok').onclick=()=>{result=true;d.close();};$('#confirm-cancel').onclick=()=>d.close();d.addEventListener('close',()=>resolve(result),{once:true});});}
async function run(task){try{await task();}catch(e){toast(e.message);}}
function heading(title,description,action=''){return `<div class="page-heading"><div><span class="eyebrow">The studio workspace</span><h2>${title}</h2><p>${description}</p></div>${action}</div>`;}
function showTab(next){tab=next;document.querySelectorAll('[data-tab]').forEach(b=>{if(b.dataset.tab===tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});render();}
function render(){const c=$('#content'),p=state.draft.projects;
 if(tab==='overview'){c.innerHTML=heading('Make room for ideas.','Manage your work, update your story and publish when everything feels right.')+`<div class="welcome-banner"><div><span class="eyebrow">Your portfolio, considered</span><h2>The next chapter<br>starts here.</h2><p>Your saved drafts stay private until you publish. Explore a preview of either page before sharing your changes.</p><div class="quick-actions"><button class="primary" data-go="projects">Manage projects ↗</button><button class="secondary" data-go="pages">Edit your pages</button></div></div><img src="${esc(state.draft.settings.dayPoster)}" alt="Architecture preview"></div><div class="stats"><div class="stat"><strong>${p.length}</strong><span>PROJECTS IN COLLECTION</span></div><div class="stat"><strong>${p.reduce((n,p)=>n+p.images.length,0)}</strong><span>PROJECT IMAGES</span></div><div class="stat"><strong>${state.history.length}</strong><span>PUBLISH BACKUPS</span></div></div><div class="panel"><h3>A simple publishing rhythm.</h3><p>1. Edit your content. &nbsp; 2. Save a draft. &nbsp; 3. Preview your pages. &nbsp; 4. Publish changes.</p><p>Every publish keeps the previous version in Backups. Restore it to a draft whenever you need.</p></div>`;c.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showTab(b.dataset.go));}
 if(tab==='projects'){c.innerHTML=heading('The collection.','Add projects, arrange your work and choose the images that tell each story.','<button id="add-project" class="primary">+ Add project</button>')+'<div class="search-bar"><input id="project-search" type="search" placeholder="Search projects" aria-label="Search projects"></div><div class="project-list" id="project-list"></div>';$('#add-project').onclick=()=>editProject();$('#project-search').oninput=renderProjects;renderProjects();}
 if(tab==='pages'){c.innerHTML=heading('Your words. Your world.','Edit existing text, images and links while keeping the website layout intact.')+'<div class="notice">Save your draft, then open Preview home or Preview gallery to see the result. For project cards, use Projects. For page titles, videos and colour settings, use Hero & settings.</div><div class="search-bar"><select id="page-choice" aria-label="Choose page"><option value="home">Homepage</option><option value="gallery">Gallery page</option></select><input id="field-search" type="search" placeholder="Find text, section or image" aria-label="Search page content"></div><div id="page-fields" class="panel"></div>';$('#page-choice').onchange=renderFields;$('#field-search').oninput=renderFields;renderFields();}
 if(tab==='settings')renderSettings();
 if(tab==='media'){c.innerHTML=heading('The visual library.','Upload images and MP4 films, then use them in your projects or page settings.','<label class="primary file-button">+ Upload media<input id="library-upload" type="file" accept="image/jpeg,image/png,image/webp,image/avif,image/gif,video/mp4" multiple></label>')+'<p class="hint">Maximum 100 MB per file. Uploads remain available when a project is removed.</p><div id="library-grid" class="media-grid"></div>';$('#library-upload').onchange=e=>run(async()=>{for(const file of e.target.files)await upload(file);await loadMedia();renderLibrary();toast('Media uploaded.');});run(async()=>{await loadMedia();renderLibrary();});}
 if(tab==='backups'){c.innerHTML=heading('Room to rewind.','Every publish keeps the previous live version. Restore it into a draft, review it, then publish.')+`<div class="panel"><h3>Keep a content backup.</h3><p>Download project details and page settings. Media files stay on your server; back up the cms-data folder separately to preserve uploaded files.</p><div class="quick-actions"><a class="secondary" href="/api/admin/export" download>Download saved draft</a><label class="secondary file-button">Import content backup<input id="import-backup" type="file" accept="application/json"></label></div></div><div class="panel"><h3>Previous live versions</h3>${state.history.map(h=>`<div class="backup-row"><p>${esc(new Date(h.date).toLocaleString())}</p><button class="secondary" data-restore="${h.id}">Restore to draft</button></div>`).join('')||'<p>Your first backup will appear after publishing.</p>'}</div>`;c.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>run(async()=>{if(await confirmAction('Restore this version?','This replaces your current draft. The live website stays unchanged until you publish.')){accept(await api('restore','POST',{id:b.dataset.restore,version:state.version}));render();toast('Backup restored to draft.');}}));$('#import-backup').onchange=e=>run(async()=>{const file=e.target.files[0];if(!file)return;if(await confirmAction('Import content backup?','Your current draft will be replaced. Media referenced by the backup must already exist on this server.')){accept(await api('import','POST',{version:state.version,backup:JSON.parse(await file.text())}));render();toast('Backup imported to draft.');}});}
}
function renderProjects(){const q=$('#project-search').value.toLowerCase();$('#project-list').innerHTML=state.draft.projects.map((p,i)=>({p,i})).filter(({p})=>(p.title+' '+p.category).toLowerCase().includes(q)).map(({p,i})=>`<article class="admin-project"><img src="${esc(p.images[0]?.src)}" alt="${esc(p.title)}" loading="lazy"><div class="project-summary"><h3>${esc(p.title)}</h3><p>${esc(p.category)} · ${p.images.length} views · ${p.published===false?'Hidden':'Visible'}</p><div class="card-actions"><button class="secondary" data-edit="${i}">Edit</button><button class="secondary" data-move="${i}" data-delta="-1" ${i===0?'disabled':''} aria-label="Move ${esc(p.title)} earlier">↑</button><button class="secondary" data-move="${i}" data-delta="1" ${i===state.draft.projects.length-1?'disabled':''} aria-label="Move ${esc(p.title)} later">↓</button><button class="secondary danger" data-delete="${i}">Delete</button></div></div></article>`).join('')||'<p class="empty-state">No projects found.</p>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editProject(+b.dataset.edit));document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const i=+b.dataset.move,j=i+(+b.dataset.delta);[state.draft.projects[i],state.draft.projects[j]]=[state.draft.projects[j],state.draft.projects[i]];changed();renderProjects();});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>run(async()=>{const i=+b.dataset.delete;if(await confirmAction('Remove this project?',`“${state.draft.projects[i].title}” will be removed from the draft. Publish to remove it from the gallery. Its uploaded images remain in the library.`)){state.draft.projects.splice(i,1);changed();renderProjects();}}));}
function editProject(index){editing={index,project:index===undefined?{id:'project-'+crypto.randomUUID().slice(0,8),title:'',category:'Architecture',description:'',published:true,images:[]}:structuredClone(state.draft.projects[index])};const f=$('#project-form');f.elements.title.value=editing.project.title;f.elements.category.value=editing.project.category;f.elements.description.value=editing.project.description;f.elements.published.checked=editing.project.published!==false;$('#project-dialog-title').textContent=index===undefined?'A new project.':'Edit project.';$('#project-error').textContent='';$('#project-files').value='';renderImages();$('#project-dialog').showModal();}
function renderImages(){$('#project-images').innerHTML=editing.project.images.map((i,n)=>`<div class="edit-image"><img src="${esc(i.src)}" alt="${esc(i.alt)}"><div class="badge">${n===0?'Cover image':'View '+(n+1)}</div><input data-image-alt="${n}" aria-label="Image ${n+1} description" value="${esc(i.alt)}" maxlength="400"><div class="card-actions"><button type="button" class="secondary" data-img-move="${n}" data-delta="-1" ${n===0?'disabled':''} aria-label="Move image ${n+1} earlier">↑</button><button type="button" class="secondary" data-img-move="${n}" data-delta="1" ${n===editing.project.images.length-1?'disabled':''} aria-label="Move image ${n+1} later">↓</button><button type="button" class="secondary danger" data-img-remove="${n}">Remove</button></div></div>`).join('')||'<p class="empty-state">Add your first image to give this project a cover.</p>';document.querySelectorAll('[data-image-alt]').forEach(e=>e.oninput=()=>editing.project.images[+e.dataset.imageAlt].alt=e.value);document.querySelectorAll('[data-img-remove]').forEach(b=>b.onclick=()=>{editing.project.images.splice(+b.dataset.imgRemove,1);renderImages();});document.querySelectorAll('[data-img-move]').forEach(b=>b.onclick=()=>{const i=+b.dataset.imgMove,j=i+(+b.dataset.delta),a=editing.project.images;[a[i],a[j]]=[a[j],a[i]];renderImages();});}
async function dimensions(src){return new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve({width:i.naturalWidth,height:i.naturalHeight});i.onerror=()=>reject(Error('Image could not be decoded'));i.src=src;});}
async function upload(file){
 if(file.size>100*1024*1024)throw Error('Maximum upload size is 100 MB.');
 if(!/\.(jpe?g|png|webp|avif|gif|mp4)$/i.test(file.name))throw Error('Choose a JPG, PNG, WebP, AVIF, GIF or MP4 file.');
 uploading++;const submit=$('#project-form button[type="submit"]');submit.disabled=true;
 try{
  toast('Uploading '+file.name+'...');let v;
  if(window.NouvelleBlobUpload)v=await window.NouvelleBlobUpload(file,csrf,progress=>toast('Uploading '+file.name+' - '+Math.round(progress.percentage)+'%'));
  else{const r=await fetch('/api/admin/upload',{method:'POST',headers:{'X-CSRF-Token':csrf,'Content-Type':'application/octet-stream'},body:file});v=await r.json();if(!r.ok)throw Error(v.error);}
  return {src:v.src,alt:file.name.replace(/\.[^.]+$/,''),variants:[],...(v.type==='mp4'?{}:await dimensions(v.src))};
 }finally{uploading--;submit.disabled=uploading>0;}
}
async function loadMedia(){media=await api('media');}
async function pickMedia(callback,kind='image'){pickCallback=callback;await loadMedia();$('#media-title').textContent=kind==='video'?'Choose a film':'Choose an image';$('#media-dialog').dataset.kind=kind;$('#media-search').value='';renderPicker();$('#media-dialog').showModal();}
function renderPicker(){const q=$('#media-search').value.toLowerCase(),kind=$('#media-dialog').dataset.kind;$('#media-picker').innerHTML=media.map((m,n)=>({m,n})).filter(({m})=>m.type===kind&&(m.alt+' '+m.src).toLowerCase().includes(q)).map(({m,n})=>`<button class="media-item" data-pick="${n}">${m.type==='video'?`<video src="${esc(m.src)}" preload="metadata" muted></video>`:`<img src="${esc(m.src)}" alt="${esc(m.alt)}" loading="lazy">`}<span>${esc(m.alt||m.src)}</span></button>`).join('');document.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>run(async()=>{const m=media[+b.dataset.pick];const item=m.type==='image'?{src:m.src,alt:m.alt||'Project image',variants:[],...await dimensions(m.src)}:{src:m.src};await pickCallback(item);$('#media-dialog').close();}));}
function renderLibrary(){$('#library-grid').innerHTML=media.map(m=>`<div class="media-item">${m.type==='video'?`<video src="${esc(m.src)}" controls preload="metadata"></video>`:`<img src="${esc(m.src)}" alt="${esc(m.alt)}" loading="lazy">`}<span title="${esc(m.src)}">${esc(m.alt||m.src)}</span><a class="quiet-button" href="${esc(m.src)}" target="_blank" rel="noopener">Open ↗</a></div>`).join('');}
function renderFields(){const page=$('#page-choice').value,q=$('#field-search').value.toLowerCase();const fields=state.catalog.filter(f=>f.page===page&&(f.label+' '+f.section+' '+(state.draft.overrides[f.id]||'')).toLowerCase().includes(q));$('#page-fields').innerHTML=fields.map(f=>{const v=state.draft.overrides[f.id]??f.value;return `<div class="page-field"><div class="field-meta"><span>${esc(f.kind)}</span>${esc(f.section)} · ${f.ranges.length} occurrence${f.ranges.length===1?'':'s'}<button class="quiet-button" data-reset="${f.id}">Reset</button></div>${f.kind==='image'?`<div class="field-image"><img src="${esc(v.src)}" alt="${esc(v.alt)}"><div><label>Image description<input data-field-alt="${f.id}" value="${esc(v.alt)}" maxlength="400"></label><button class="secondary" data-field-image="${f.id}">Replace image</button></div></div>`:`<label>${esc(f.label)}${f.kind==='text'?`<textarea data-field="${f.id}" rows="2" maxlength="5000">${esc(v)}</textarea>`:`<input data-field="${f.id}" value="${esc(v)}" maxlength="1000">`}</label>`}</div>`;}).join('')||'<p>No matching fields.</p>';document.querySelectorAll('[data-field]').forEach(e=>e.oninput=()=>{state.draft.overrides[e.dataset.field]=e.value;changed();});document.querySelectorAll('[data-field-alt]').forEach(e=>e.oninput=()=>{const id=e.dataset.fieldAlt,f=state.catalog.find(f=>f.id===id);state.draft.overrides[id]={...(state.draft.overrides[id]||f.value),alt:e.value};changed();});document.querySelectorAll('[data-field-image]').forEach(b=>b.onclick=()=>run(()=>pickMedia(i=>{state.draft.overrides[b.dataset.fieldImage]={src:i.src,alt:i.alt};changed();renderFields();})));document.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>{delete state.draft.overrides[b.dataset.reset];changed();renderFields();});}
function renderSettings(){const s=state.draft.settings;$('#content').innerHTML=heading('Set the atmosphere.','Manage hero films, poster images, metadata, colours and the inquiry destination.')+`<div class="settings-grid">${[['day','Outdoor film'],['night','Indoor film']].map(([key,label])=>`<div class="panel"><h3>${label}</h3><video src="${esc(s[key+'Video'])}" poster="${esc(s[key+'Poster'])}" controls preload="metadata" muted></video><div class="quick-actions"><button class="secondary" data-video="${key}">Choose film</button><label class="secondary file-button">Upload MP4<input type="file" data-video-upload="${key}" accept="video/mp4"></label><button class="secondary" data-poster="${key}">Choose poster</button></div></div>`).join('')}<div class="panel wide"><h3>Brand palette</h3><div class="colour-row">${[['cream','Light background'],['navy','Text / dark'],['plum','Gallery accent']].map(([k,l])=>`<label>${l}<input type="color" data-setting="${k}" value="${esc(s[k])}"></label>`).join('')}</div><p class="hint">These colours adjust the gallery palette. The original homepage styling is preserved.</p></div><div class="panel"><h3>Homepage metadata</h3><label>Page title<input data-setting="homeTitle" value="${esc(s.homeTitle)}" maxlength="160"></label><label>Search description<textarea data-setting="homeDescription" maxlength="1000">${esc(s.homeDescription)}</textarea></label></div><div class="panel"><h3>Gallery metadata</h3><label>Page title<input data-setting="galleryTitle" value="${esc(s.galleryTitle)}" maxlength="160"></label><label>Search description<textarea data-setting="galleryDescription" maxlength="1000">${esc(s.galleryDescription)}</textarea></label></div><div class="panel wide"><h3>Project inquiries</h3><label>Recipient email<input type="email" data-setting="inquiryEmail" value="${esc(s.inquiryEmail)}"></label><p class="hint">Inquiry forms prepare an email draft for this address. Edit the displayed phone numbers, email text and contact links separately in Page editor.</p></div></div>`;document.querySelectorAll('[data-setting]').forEach(e=>e.oninput=()=>{s[e.dataset.setting]=e.value;changed();});document.querySelectorAll('[data-video]').forEach(b=>b.onclick=()=>run(()=>pickMedia(i=>{s[b.dataset.video+'Video']=i.src;changed();renderSettings();},'video')));document.querySelectorAll('[data-poster]').forEach(b=>b.onclick=()=>run(()=>pickMedia(i=>{s[b.dataset.poster+'Poster']=i.src;changed();renderSettings();})));document.querySelectorAll('[data-video-upload]').forEach(e=>e.onchange=()=>run(async()=>{if(!e.files[0])return;const v=await upload(e.files[0]);s[e.dataset.videoUpload+'Video']=v.src;changed();renderSettings();}));}
async function enter(){state=await api('state');$('#auth-screen').hidden=true;$('#workspace').hidden=false;render();}
async function boot(){try{const s=await api('session');csrf=s.csrf||'';if(s.authenticated)return enter();if(!s.configured){$('#auth-error').textContent='Administrator access is not configured. Contact the website owner.';$('#sign-in').disabled=true;}}catch(e){$('#auth-error').textContent='The admin server is unavailable. Start the Node server to manage your website.';}}
$('#auth-form').onsubmit=async e=>{e.preventDefault();$('#auth-error').textContent='';$('#sign-in').disabled=true;try{const s=await api('login','POST',{username:$('#username').value,password:$('#password').value});csrf=s.csrf;$('#password').value='';await enter();}catch(e){$('#auth-error').textContent=e.message;}finally{$('#sign-in').disabled=false;}};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#media-search').oninput=renderPicker;
$('#save-draft').onclick=()=>run(save);$('#publish').onclick=()=>run(async()=>{await publishChanges();render();});
$('#logout').onclick=()=>run(async()=>{if(dirty&&!await confirmAction('Sign out without saving?','Unsaved edits in this browser will be lost.'))return;await api('logout','POST',{});location.reload();});
$('#project-form').onsubmit=async e=>{
 e.preventDefault();if(uploading){$('#project-error').textContent='Wait for images to finish uploading.';return;}
 const f=e.target;if(!editing.project.images.length){$('#project-error').textContent='Add at least one project image.';return;}
 Object.assign(editing.project,{title:f.elements.title.value.trim(),category:f.elements.category.value.trim(),description:f.elements.description.value,published:f.elements.published.checked});
 if(!editing.project.title||!editing.project.category)return;
 const submit=f.querySelector('[type="submit"]');submit.disabled=true;$('#project-error').textContent='Saving and publishing...';
 try{
  if(editing.index===undefined){editing.index=state.draft.projects.length;state.draft.projects.push(editing.project);}else state.draft.projects[editing.index]=editing.project;
  changed();await publishChanges();$('#project-dialog').close();renderProjects();
 }catch(error){$('#project-error').textContent=error.message;}finally{submit.disabled=false;}
};
$('#project-files').onchange=e=>run(async()=>{for(const file of Array.from(e.target.files)){editing.project.images.push(await upload(file));renderImages();}toast('Images added to the project.');e.target.value='';});$('#project-library').onclick=()=>run(()=>pickMedia(i=>{editing.project.images.push(i);renderImages();}));
addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});boot();
