"""Regenerate the project gallery only from the curated project manifest (Python 3)."""
from pathlib import Path
from html import escape
import json

ROOT = Path(__file__).resolve().parent.parent
projects = json.loads((ROOT / 'assets/projects.json').read_text(encoding='utf-8'))

def image(item, eager=False, sizes='(max-width: 700px) 100vw, 65vw'):
    sources = ', '.join(f'{v["src"]} {v["width"]}w' for v in item['variants'])
    sources += f', {item["src"]} {item["width"]}w'
    return f'<img src="{item["src"]}" srcset="{sources.lstrip(", ")}" sizes="{sizes}" width="{item["width"]}" height="{item["height"]}" alt="{escape(item["alt"])}" loading="{"eager" if eager else "lazy"}" decoding="async" {"fetchpriority=high" if eager else ""}>'

def header(gallery):
    return f'''<a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><a class="wordmark" href="/" aria-label="Nouvelle Spaces home">nouvelle<span>SPACES</span></a>
<button class="menu-toggle" aria-expanded="false" aria-controls="navigation" hidden>Menu <span>+</span></button>
<nav id="navigation" aria-label="Main navigation"><a href="/" {'' if gallery else 'aria-current="page"'}>Home</a><a href="/projects" {'aria-current="page"' if gallery else ''}>Projects <sup>{len(projects):02}</sup></a><a href="/#studio">The studio</a><a class="nav-contact" href="#contact">Let’s talk <span aria-hidden="true">↗</span></a></nav></header>'''

def footer():
    return '''<section class="contact section-pad" id="contact" aria-labelledby="contact-title"><div class="eyebrow">A new perspective starts with a conversation</div><div class="contact-top"><h2 id="contact-title">Let’s make<br><em>room for ideas.</em></h2><a class="round-link" href="mailto:Syedain9988@gmail.com" aria-label="Email the studio">↗</a></div><div class="contact-bottom"><p>Tell us what you have in mind.<br>We’ll explore the possibilities together.</p><button class="text-link" data-inquiry>Start a project <span aria-hidden="true">↗</span></button></div><div class="contact-people"><div><span class="eyebrow">Umais Ali</span><a href="mailto:umais.ali80@gmail.com">umais.ali80@gmail.com</a><a href="tel:+923130371049">+92 313 0371049</a></div><div><span class="eyebrow">Syed Ain</span><a href="mailto:Syedain9988@gmail.com">Syedain9988@gmail.com</a><a href="tel:+923435291533">+92 343 5291533</a></div></div></section>
<footer class="site-footer"><a class="wordmark" href="/">nouvelle<span>SPACES</span></a><p>Architecture. Interiors. Visualization.</p><a href="#top">Back to top ↑</a></footer>
<dialog id="inquiry" aria-labelledby="inquiry-title" data-lenis-prevent><button class="dialog-close" data-close aria-label="Close inquiry">×</button><div class="eyebrow">Begin a conversation</div><h2 id="inquiry-title">Your next space.</h2><p>Share a few details to prepare an email to the studio.</p><form id="inquiry-form"><label>Name<input name="name" autocomplete="name" required maxlength="120"></label><label>Email<input name="email" type="email" autocomplete="email" required maxlength="200"></label><label>Phone <span>(optional)</span><input name="phone" type="tel" autocomplete="tel" maxlength="40"></label><label>Tell us about your project<textarea name="message" rows="3" required maxlength="3000"></textarea></label><button class="solid-button" type="submit">Prepare email <span>↗</span></button><p class="form-note">Nothing is sent here. You’ll review and send the message in your email app.</p></form><div id="email-result" hidden role="status"><p>Your draft is ready. Open your email app to review and send it.</p><a class="solid-button" id="draft-link">Open email draft ↗</a><button class="text-link" id="copy-inquiry">Copy message</button><p>Or email <a href="mailto:Syedain9988@gmail.com">Syedain9988@gmail.com</a> directly.</p></div></dialog>'''

def card(p, n, home=False):
    target = '/projects#' + p['id'] if home else p['images'][0]['src']
    return f'''<article class="project-card" id="{p['id']}" data-category="{p['category']}"><a class="project-image" href="{target}" {'' if home else 'data-project="'+p['id']+'"'} aria-label="Explore {escape(p['title'])}">{image(p['images'][0])}<span class="image-cta">{'Explore project' if home else 'View project'} <span>↗</span></span></a><div class="project-meta"><span class="project-number">{n:02}</span><div><h{'3' if home else '2'}><a href="{target}" {'' if home else 'data-project="'+p['id']+'"'}>{p['title']}</a></h{'3' if home else '2'}><p>{p['category']} <span>·</span> {len(p['images']):02} {'view' if len(p['images']) == 1 else 'views'}</p></div><span aria-hidden="true">↗</span></div>{'' if home else '<p class="project-description">'+p['description']+'</p>'}</article>'''

def page(gallery=False):
    title = 'Selected projects' if gallery else 'Architecture, interiors & visualization'
    start = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#f3f3ec"><title>Nouvelle Spaces — {title}</title><meta name="description" content="Explore Nouvelle Spaces: architecture, considered interiors and atmospheric 3D visualization. Discover the selected portfolio and speak with the studio."><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/css/projects.css"><link rel="stylesheet" href="/css/site-theme.css"><script src="/js/gallery-loader.js" defer></script><script src="/js/gsap.min.js" defer></script><script src="/js/ScrollTrigger.min.js" defer></script><script src="/js/lenis.min.js" defer></script><script src="/js/projects.js" defer></script></head><body id="top" class="{'gallery-page' if gallery else 'home-page'}">{header(gallery)}<main id="main">'''
    if gallery:
        total = sum(len(p['images']) for p in projects)
        filters = ''.join(f'<button aria-pressed="false" data-filter="{escape(c)}">{escape(c)}</button>' for c in dict.fromkeys(p['category'] for p in projects))
        content = f'''<section class="gallery-intro section-pad"><div class="eyebrow"><span class="small-star">&#10035;</span> The Nouvelle collection / 01&mdash;{len(projects):02}</div><div class="gallery-heading"><h1>Spaces with<br><em>a point of view.</em></h1><p>Architecture, interiors and imagined worlds.<br>A collection of spaces, seen through our lens.</p></div><div class="gallery-scene" aria-label="A glimpse of our collection"><div class="scene-orbit" aria-hidden="true"></div><span class="scene-coordinate" aria-hidden="true">FORM / LIGHT / ATMOSPHERE</span><a href="#collection" class="scene-frame scene-left" aria-label="Explore architectural projects">{image(projects[6]['images'][0],True)}</a><a href="#collection" class="scene-frame scene-main" aria-label="Explore the complete collection">{image(projects[1]['images'][0],True)}<span>Discover the collection &#8595;</span></a><a href="#collection" class="scene-frame scene-right" aria-label="Explore interior projects">{image(projects[4]['images'][0],True)}</a><span class="scene-caption">Designed to be experienced.</span></div><div class="gallery-intro-bottom"><span>{len(projects):02} projects &nbsp; / &nbsp; {total} perspectives</span><button id="motion-toggle" aria-pressed="false" hidden>Pause motion</button><a href="#collection">Explore the collection &#8595;</a></div></section><section id="collection" class="collection section-pad" aria-label="Project collection"><div class="collection-heading"><div><div class="eyebrow">The portfolio</div><h2>Every space.<br><em>A different story.</em></h2></div><p>From the first architectural gesture to the smallest interior detail. Step inside each project.</p></div><div class="filter-bar" hidden><div role="group" aria-label="Filter projects"><button aria-pressed="true" data-filter="All">All projects <sup>{len(projects):02}</sup></button>{filters}</div><p id="result-count" role="status" aria-live="polite">{len(projects):02} projects</p></div><div class="project-grid">'''
        content += ''.join(card(p,i+1) for i,p in enumerate(projects))
        content += '''</div><div class="collection-end"><span>End of collection</span><span>Every space begins with possibility.</span><a href="#contact">What’s yours? ↗</a></div></section>'''
    viewer = '''<dialog id="project-viewer" aria-labelledby="viewer-title" data-lenis-prevent><div class="viewer-top"><span class="eyebrow" id="viewer-category"></span><button class="dialog-close" data-close aria-label="Close project">×</button></div><div class="viewer-layout"><div class="viewer-stage"><img id="viewer-image" alt=""><div class="viewer-controls"><button id="previous-image" aria-label="Previous image">←</button><span id="viewer-count" role="status" aria-live="polite"></span><button id="next-image" aria-label="Next image">→</button></div></div><div class="viewer-info"><span class="eyebrow">Project study</span><h2 id="viewer-title"></h2><p id="viewer-description"></p><div class="thumbnails" aria-label="Project images"></div><a class="text-link" id="original-image" target="_blank" rel="noopener">Open full-size image ↗</a><p id="viewer-caption" class="viewer-source"></p><p class="viewer-hint">Use ← → to browse · Esc to close</p></div></div></dialog>'''
    return start + content + '</main>' + footer() + (viewer if gallery else '') + '</body></html>\n'

for filename,gallery in [('projects.html',True)]:
    (ROOT / filename).write_text(page(gallery),encoding='utf-8')
